---
# tasks file for wordpress-mysql

#task to launch mysql 
  - name: "Launching MySql"
    shell: "kubectl run mydb --image=mysql:5.7 --env=MYSQL_ROOT_PASSWORD={{ password }}   --env=MYSQL_DATABASE=wpdb  --env=MYSQL_USER=hrishabh  --env=MYSQL_PASSWORD={{ password }}"
    register: MySQL
  - debug:
      var: "MySQL.stdout_lines"


#task to launch wordpress
  - name: "Launching Wordpress"
    shell: "kubectl run mywp --image=wordpress:5.1.1-php7.3-apache"
    register: wordpress
  - debug:
      var: "wordpress.stdout_lines"

# Exposing Wordpress
  - name: "Exposing wordpress"
    shell: "kubectl expose pods mywp  --type=NodePort  --port=80"
    register: exposed
    ignore_errors: yes
  - debug: 
      var: "exposed.stdout_lines"

  - name: "get service"
    shell: "kubectl get svc"
    register: svc
  - debug:
      var: "svc.stdout_lines"

  - name: "Pausing playbook for 60 seconds"
    pause: 
      seconds: 60

  - name: "Getting Database IP"
    shell: "kubectl get pods -o wide"
    register: Database_IP
  - debug:
      var: "Database_IP.stdout_lines"



